### ISSUE TITLE
Discord Server Link Expired

### ISSUE THREAD

**Issue by theonepacman** [OpenColonyShip/OpenColonyShip#1]
the discord server link has expired ensure to make it permanet

**Comment by microlith57** [comment]
Congratulations! Issue 1! Will fix soon.

**Comment by ShortCircuitSam** [comment]
Sorry to be a pain, but I don’t seem to be able to edit things? Like, I can’t actually create a folder.

**Comment by microlith57** [comment]
Fixed.

**Comment by microlith57** [comment]
Closes #1

**Comment by microlith57** [comment]
help
i cant close the issue

**Comment by ShortCircuitSam** [comment]
There we go!

**Comment by ShortCircuitSam** [comment]
I just went close by the comment button

**Comment by microlith57** [comment]
Thanks
